version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: docker-mysql
    ports:
      - '3306:3306'
    environment:
#      MYSQL_DATABASE: inventory_service
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
